version: 1.0.{build}
image: Visual Studio 2019
cache: C:/Tools/vcpkg/installed
environment:
  VCPKG_DEFAULT_TRIPLET: $(platform)-windows-static
install:
  - vcpkg integrate install
  - vcpkg install boost-regex
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
build:
  project: ffftp.sln
  verbosity: minimal
test: off
artifacts:
  - path: $(configuration)\ffftp-*.*
    name: binary
    type: file
  - path: $(configuration)\*\ffftp.pdb
    name: pdb
    type: file
deploy: off
for:
  - matrix:
      only:
        - platform: Win32
    environment:
      VCPKG_DEFAULT_TRIPLET: x86-windows-static
