name: CI
on: push
jobs:
  build:
    strategy:
      matrix:
        platform:
        - x86
        - x64
        configuration:
        - Debug
        - Release
    runs-on: windows-latest
    steps:
    - name: Get vcpkg dir
      id: cache
      run: echo "::set-output name=dir::$env:VCPKG_INSTALLATION_ROOT"
    - name: Enable cache
      uses: actions/cache@v1.0.3
      with:
        key: vcpkg-${{matrix.platform}}
        path: ${{steps.cache.outputs.dir}}\installed
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      run: |
        $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
        vcpkg integrate install
        vcpkg install boost-regex:${{matrix.platform}}-windows-static
        MSBuild ffftp.sln /p:Platform=$('${{matrix.platform}}' -replace 'x86', 'Win32') /p:Configuration=${{matrix.configuration}}
        mv ${{matrix.configuration}}\${{matrix.platform}}\ffftp.pdb ${{matrix.configuration}}\ffftp-${{matrix.platform}}.pdb
    - name: Upload msi
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v1
      with:
        name: ${{matrix.platform}}-msi
        path: ${{matrix.configuration}}/ffftp-${{matrix.platform}}.msi
    - name: Upload zip
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v1
      with:
        name: ${{matrix.platform}}-zip
        path: ${{matrix.configuration}}/ffftp-${{matrix.platform}}.zip
    - name: Upload pdb
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v1
      with:
        name: ${{matrix.platform}}-pdb
        path: ${{matrix.configuration}}/ffftp-${{matrix.platform}}.pdb
