name: CD
on:
  release:
    types:
    - published
jobs:
  build:
    strategy:
      matrix:
        platform:
        - x86
        - x64
        configuration:
#       - Debug
        - Release
    runs-on: windows-latest
    steps:
#   - name: Get vcpkg dir
#     id: vcpkg
#     run: echo "::set-output name=dir::$env:VCPKG_INSTALLATION_ROOT"
#   - name: Enable cache
#     uses: actions/cache@v1.0.3
#     with:
#       key: vcpkg-${{matrix.platform}}
#       path: ${{steps.vcpkg.outputs.dir}}\installed
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        $env:Path += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin"
        vcpkg integrate install
        vcpkg --overlay-triplets=vcpkg/triplets install boost-regex:${{matrix.platform}}-windows-ffftp
        MSBuild ffftp.sln /p:Platform=$('${{matrix.platform}}' -replace 'x86', 'Win32') /p:Configuration=${{matrix.configuration}}
        mv ${{matrix.configuration}}\${{matrix.platform}}\ffftp.pdb ${{matrix.configuration}}\ffftp-${{matrix.platform}}.pdb
    - name: Upload msi
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{github.event.release.upload_url}}
        asset_path: ${{matrix.configuration}}/ffftp-${{matrix.platform}}.msi
        asset_name: ffftp-${{github.event.release.tag_name}}-${{matrix.platform}}.msi
        asset_content_type: application/octet-stream
    - name: Upload zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{github.event.release.upload_url}}
        asset_path: ${{matrix.configuration}}/ffftp-${{matrix.platform}}.zip
        asset_name: ffftp-${{github.event.release.tag_name}}-${{matrix.platform}}.zip
        asset_content_type: application/zip
    - name: Upload pdb
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{github.event.release.upload_url}}
        asset_path: ${{matrix.configuration}}/ffftp-${{matrix.platform}}.pdb
        asset_name: ffftp-${{github.event.release.tag_name}}-${{matrix.platform}}.pdb
        asset_content_type: application/octet-stream
